import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { useMemo, useState } from "react";
import {
  IndianRupee, AlertCircle, CheckCircle2, TrendingUp, Plus, Search,
  Printer, Trash2, Pencil, FileText, Copy,
} from "lucide-react";
import { toast } from "sonner";
import { Shell } from "@/components/layout/Shell";
import { StatCard } from "@/components/ui-blocks/StatCard";
import { SkeletonStatCard, SkeletonRow } from "@/components/ui-blocks/SkeletonCard";
import { Modal, useModal } from "@/components/ui-blocks/Modal";
import {
  usePayments, useSavePayment, useDeletePayment,
  useStudents, useSettings,
  type PaymentRow, type PaymentInput,
} from "@/lib/queries";

export const Route = createFileRoute("/payments")({
  head: () => ({ meta: [{ title: "Payments — Study Lounge OS" }] }),
  component: Payments,
});

const typeLabels: Record<string, string> = {
  monthly_fee: "Monthly Fee",
  admission: "Admission",
  security_deposit: "Deposit",
  misc: "Misc",
};
const methodLabels: Record<string, string> = {
  cash: "Cash",
  upi: "UPI",
  bank_transfer: "Bank",
};
const statusStyle: Record<string, { cls: string; label: string }> = {
  paid: { cls: "bg-[oklch(0.72_0.18_155/0.15)] text-[oklch(0.85_0.18_155)]", label: "Paid" },
  partial: { cls: "bg-[oklch(0.82_0.17_80/0.15)] text-[oklch(0.92_0.17_80)]", label: "Partial" },
  overdue: { cls: "bg-[oklch(0.65_0.24_25/0.15)] text-[oklch(0.85_0.20_25)]", label: "Overdue" },
};
const fmt = (n: number) =>
  `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;

function printReceipt(p: PaymentRow, loungeName: string) {
  const w = window.open("", "_blank", "width=420,height=640");
  if (!w) { toast.error("Allow pop-ups to print receipts"); return; }
  const rn = p.receipt_number ?? `RCP-${p.id.slice(0, 8).toUpperCase()}`;
  w.document.write(`<!DOCTYPE html><html><head><title>Receipt ${rn}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:monospace;padding:24px 20px;font-size:13px;color:#000}
h1{font-size:17px;text-align:center;margin-bottom:4px}
.sub{text-align:center;font-size:11px;color:#555;margin-bottom:12px}
.divider{border-top:1px dashed #999;margin:10px 0}
.row{display:flex;justify-content:space-between;padding:3px 0}
.amount{font-size:26px;font-weight:bold;text-align:center;margin:14px 0;letter-spacing:-1px}
.badge{border:1.5px solid #000;display:inline-block;padding:2px 10px;border-radius:4px;font-weight:bold}
.footer{text-align:center;font-size:10px;color:#888;margin-top:16px}
@media print{body{padding:8px}}
</style></head><body>
<h1>${loungeName || "Study Lounge OS"}</h1>
<div class="sub">OFFICIAL PAYMENT RECEIPT</div>
<div class="divider"></div>
<div class="row"><span>Receipt #</span><span><b>${rn}</b></span></div>
<div class="row"><span>Date</span><span>${p.payment_date}</span></div>
<div class="divider"></div>
<div class="row"><span>Student</span><span>${p.students?.name ?? "—"}</span></div>
<div class="row"><span>Phone</span><span>${p.students?.phone ?? "—"}</span></div>
<div class="divider"></div>
<div class="amount">${fmt(Number(p.amount))}</div>
<div class="row"><span>Type</span><span>${typeLabels[p.payment_type] ?? p.payment_type}</span></div>
<div class="row"><span>Method</span><span>${methodLabels[p.payment_method] ?? p.payment_method}</span></div>
<div class="row"><span>Status</span><span class="badge">${p.status.toUpperCase()}</span></div>
${p.due_date ? `<div class="row"><span>Due Date</span><span>${p.due_date}</span></div>` : ""}
${p.notes ? `<div class="divider"></div><div class="row"><span>Notes</span><span>${p.notes}</span></div>` : ""}
<div class="divider"></div>
<div class="footer">Thank you for your payment<br>Generated by Study Lounge OS</div>
<script>window.onload=()=>{window.print()}</script>
</body></html>`);
  w.document.close();
}

function MigrationBanner({ sql }: { sql: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-[oklch(0.82_0.17_80/0.3)] bg-[oklch(0.82_0.17_80/0.06)] p-6">
      <div className="flex items-center gap-3">
        <div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[oklch(0.82_0.17_80/0.2)]">
          <FileText className="h-5 w-5 text-[oklch(0.92_0.17_80)]" />
        </div>
        <div>
          <div className="font-display text-base font-semibold">Database setup required</div>
          <div className="mt-0.5 text-sm text-muted-foreground">
            Run the SQL below in your <strong>Supabase SQL Editor</strong> to enable Payments &amp; Attendance.
          </div>
        </div>
        <button onClick={copy}
          className="ml-auto inline-flex items-center gap-1.5 rounded-xl glass px-3 py-2 text-xs transition hover:bg-white/8">
          {copied ? <CheckCircle2 className="h-3.5 w-3.5 text-[oklch(0.85_0.18_155)]" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? "Copied!" : "Copy SQL"}
        </button>
      </div>
      <div className="mt-4 max-h-64 overflow-auto rounded-xl bg-black/40 p-4 scrollbar-thin">
        <pre className="text-[11px] leading-relaxed text-[oklch(0.78_0.18_155)]">{sql}</pre>
      </div>
      <div className="mt-3 text-xs text-muted-foreground">
        📍 Supabase Dashboard → SQL Editor → New query → Paste → Run. Then refresh this page.
      </div>
    </motion.div>
  );
}

function Payments() {
  const { data: payments = [], isLoading, isError } = usePayments();
  const { data: students = [] } = useStudents();
  const { data: settings } = useSettings();
  const savePayment = useSavePayment();
  const deletePayment = useDeletePayment();
  const modal = useModal();
  const [editing, setEditing] = useState<PaymentRow | null>(null);
  const [filter, setFilter] = useState<"all" | "this_month" | "paid" | "partial" | "overdue">("all");
  const [q, setQ] = useState("");

  const today = new Date();
  const monthStart = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().slice(0, 10);

  const stats = useMemo(() => {
    const monthRevenue = payments
      .filter((p) => p.payment_date >= monthStart && p.status === "paid")
      .reduce((s, p) => s + Number(p.amount), 0);
    const outstanding = payments
      .filter((p) => p.status === "partial" || p.status === "overdue")
      .reduce((s, p) => s + Number(p.amount), 0);
    const paidThisMonth = payments.filter((p) => p.payment_date >= monthStart && p.status === "paid").length;
    const totalThisMonth = payments.filter((p) => p.payment_date >= monthStart).length;
    const rate = totalThisMonth > 0 ? Math.round((paidThisMonth / totalThisMonth) * 100) : 0;
    return { monthRevenue, outstanding, paidThisMonth, rate };
  }, [payments, monthStart]);

  const filtered = useMemo(() => payments.filter((p) => {
    const matchQ = !q || (p.students?.name ?? "").toLowerCase().includes(q.toLowerCase()) || (p.students?.phone ?? "").includes(q);
    const matchF = filter === "all" ? true
      : filter === "this_month" ? p.payment_date >= monthStart
      : p.status === filter;
    return matchQ && matchF;
  }), [payments, q, filter, monthStart]);

  const openAdd = () => { setEditing(null); modal.show(); };
  const openEdit = (p: PaymentRow) => { setEditing(p); modal.show(); };

  if (isError) {
    return (
      <Shell title="Payment Management" subtitle="Track fees, receipts, and dues.">
        <MigrationBanner sql={MIGRATION_SQL} />
      </Shell>
    );
  }

  return (
    <Shell title="Payment Management" subtitle="Track fees, receipts, and dues.">
      {/* Stat cards */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {isLoading ? (
          Array.from({ length: 4 }).map((_, i) => <SkeletonStatCard key={i} />)
        ) : (
          <>
            <StatCard label="Monthly Revenue" value={fmt(stats.monthRevenue)} icon={IndianRupee} accent="success" index={0} />
            <StatCard label="Outstanding Dues" value={fmt(stats.outstanding)} icon={AlertCircle} accent="warning" index={1} />
            <StatCard label="Paid This Month" value={stats.paidThisMonth} icon={CheckCircle2} accent="cyan" index={2} />
            <StatCard label="Collection Rate" value={`${stats.rate}%`} icon={TrendingUp} accent="violet" index={3} />
          </>
        )}
      </div>

      {/* Filter + search + add */}
      <div className="mt-6 flex flex-wrap items-center gap-2">
        <div className="flex items-center gap-2 rounded-xl glass px-3 py-2 md:max-w-sm flex-1">
          <Search className="h-4 w-4 shrink-0 text-muted-foreground" />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search student…"
            className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" />
        </div>
        <div className="flex flex-wrap gap-1 rounded-xl glass p-1">
          {(["all", "this_month", "paid", "partial", "overdue"] as const).map((f) => (
            <button key={f} onClick={() => setFilter(f)}
              className={`relative rounded-lg px-2.5 py-1 text-xs transition ${filter === f ? "text-foreground" : "text-muted-foreground hover:text-foreground"}`}>
              {filter === f && <motion.span layoutId="pay-filter" className="absolute inset-0 -z-0 rounded-lg bg-white/10" />}
              <span className="relative z-10 capitalize">{f === "this_month" ? "This Month" : f}</span>
            </button>
          ))}
        </div>
        <button onClick={openAdd}
          className="ml-auto inline-flex items-center gap-2 rounded-xl gradient-primary px-3 py-2 text-sm font-medium text-white glow-violet">
          <Plus className="h-4 w-4" /> Record Payment
        </button>
      </div>

      {/* Table */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }}
        className="mt-4 overflow-hidden rounded-2xl glass">
        {isLoading ? (
          <div className="divide-y divide-white/5">
            {Array.from({ length: 8 }).map((_, i) => <SkeletonRow key={i} />)}
          </div>
        ) : (
          <div className="overflow-x-auto scrollbar-thin">
            <table className="w-full min-w-[860px] text-sm">
              <thead>
                <tr className="border-b border-white/5 text-left text-[11px] uppercase tracking-wider text-muted-foreground">
                  <th className="px-5 py-3 font-medium">Student</th>
                  <th className="px-5 py-3 font-medium">Amount</th>
                  <th className="px-5 py-3 font-medium">Type</th>
                  <th className="px-5 py-3 font-medium">Method</th>
                  <th className="px-5 py-3 font-medium">Date</th>
                  <th className="px-5 py-3 font-medium">Status</th>
                  <th className="px-5 py-3 font-medium text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((p, i) => {
                  const ss = statusStyle[p.status] ?? statusStyle.paid;
                  return (
                    <motion.tr key={p.id} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.18, delay: i * 0.012 }}
                      className="border-b border-white/5 last:border-0 hover:bg-white/[0.03]">
                      <td className="px-5 py-3">
                        <div className="flex items-center gap-3">
                          <div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg gradient-primary text-[11px] font-semibold text-white">
                            {(p.students?.name ?? "?").split(" ").map((x) => x[0]).slice(0, 2).join("")}
                          </div>
                          <div>
                            <div className="font-medium">{p.students?.name ?? "—"}</div>
                            <div className="text-[11px] text-muted-foreground">{p.students?.phone ?? ""}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-3 font-display font-semibold">{fmt(Number(p.amount))}</td>
                      <td className="px-5 py-3">
                        <span className="rounded-md bg-white/8 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider">
                          {typeLabels[p.payment_type] ?? p.payment_type}
                        </span>
                      </td>
                      <td className="px-5 py-3">
                        <span className="rounded-md bg-white/8 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider">
                          {methodLabels[p.payment_method] ?? p.payment_method}
                        </span>
                      </td>
                      <td className="px-5 py-3 text-muted-foreground">{p.payment_date}</td>
                      <td className="px-5 py-3">
                        <span className={`rounded-md px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider ${ss.cls}`}>
                          {ss.label}
                        </span>
                      </td>
                      <td className="px-5 py-3">
                        <div className="flex justify-end gap-1.5">
                          <button onClick={() => printReceipt(p, settings?.library_name ?? "")}
                            className="grid h-8 w-8 place-items-center rounded-lg glass hover:bg-white/5 transition"
                            title="Print receipt">
                            <Printer className="h-3.5 w-3.5 text-[oklch(0.78_0.18_155)]" />
                          </button>
                          <button onClick={() => openEdit(p)}
                            className="grid h-8 w-8 place-items-center rounded-lg glass hover:bg-white/5 transition">
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                          <button onClick={async () => {
                            if (!confirm("Delete this payment record?")) return;
                            await deletePayment.mutateAsync(p.id);
                            toast.success("Payment deleted");
                          }} className="grid h-8 w-8 place-items-center rounded-lg glass hover:bg-white/5 transition">
                            <Trash2 className="h-3.5 w-3.5 text-[oklch(0.85_0.20_25)]" />
                          </button>
                        </div>
                      </td>
                    </motion.tr>
                  );
                })}
                {filtered.length === 0 && !isLoading && (
                  <tr>
                    <td colSpan={7} className="px-5 py-14 text-center">
                      <div className="text-sm font-medium">No payments found</div>
                      <div className="mt-1 text-xs text-muted-foreground">
                        {payments.length === 0 ? "Record your first payment above." : "Adjust the filter or search."}
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </motion.div>

      {/* Modal */}
      <Modal open={modal.open} onClose={modal.hide} title={editing ? "Edit payment" : "Record payment"}>
        <PaymentForm
          key={editing?.id ?? "new"}
          initial={editing}
          students={students}
          onSubmit={async (input) => {
            try {
              await savePayment.mutateAsync({ id: editing?.id, input });
              toast.success(editing ? "Payment updated" : "Payment recorded");
              modal.hide();
            } catch (err) {
              toast.error(err instanceof Error ? err.message : "Failed");
            }
          }}
          busy={savePayment.isPending}
        />
      </Modal>
    </Shell>
  );
}

function PaymentForm({
  initial, students, onSubmit, busy,
}: {
  initial: PaymentRow | null;
  students: { id: string; name: string; phone: string }[];
  onSubmit: (i: PaymentInput) => void;
  busy: boolean;
}) {
  const [studentId, setStudentId] = useState(initial?.student_id ?? "");
  const [amount, setAmount] = useState(String(initial?.amount ?? ""));
  const [type, setType] = useState(initial?.payment_type ?? "monthly_fee");
  const [method, setMethod] = useState(initial?.payment_method ?? "cash");
  const [date, setDate] = useState(initial?.payment_date ?? new Date().toISOString().slice(0, 10));
  const [dueDate, setDueDate] = useState(initial?.due_date ?? "");
  const [status, setStatus] = useState(initial?.status ?? "paid");
  const [notes, setNotes] = useState(initial?.notes ?? "");
  const [stuSearch, setStuSearch] = useState("");

  const filteredStudents = students.filter((s) =>
    !stuSearch || s.name.toLowerCase().includes(stuSearch.toLowerCase()) || s.phone.includes(stuSearch),
  );

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!studentId) { toast.error("Select a student"); return; }
    if (!amount || isNaN(Number(amount)) || Number(amount) <= 0) { toast.error("Enter a valid amount"); return; }
    onSubmit({
      student_id: studentId,
      amount: Number(amount),
      payment_type: type,
      payment_method: method,
      payment_date: date,
      due_date: dueDate || null,
      status,
      notes: notes.trim() || null,
    });
  };

  return (
    <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2">
      <div className="sm:col-span-2">
        <PField label="Student">
          <input value={stuSearch} onChange={(e) => setStuSearch(e.target.value)}
            placeholder="Search student…" className="w-full bg-transparent text-sm outline-none mb-1.5 pb-1.5 border-b border-white/10" />
          <select required value={studentId} onChange={(e) => setStudentId(e.target.value)}
            className="w-full bg-transparent text-sm outline-none">
            <option value="" className="bg-[oklch(0.20_0.03_270)]">— Select student —</option>
            {filteredStudents.map((s) => (
              <option key={s.id} value={s.id} className="bg-[oklch(0.20_0.03_270)]">{s.name} ({s.phone})</option>
            ))}
          </select>
        </PField>
      </div>
      <PField label="Amount (₹)">
        <input required type="number" min="0" step="0.01" value={amount}
          onChange={(e) => setAmount(e.target.value)} placeholder="1500"
          className="w-full bg-transparent text-sm outline-none" />
      </PField>
      <PField label="Status">
        <select value={status} onChange={(e) => setStatus(e.target.value)}
          className="w-full bg-transparent text-sm outline-none">
          <option value="paid" className="bg-[oklch(0.20_0.03_270)]">Paid</option>
          <option value="partial" className="bg-[oklch(0.20_0.03_270)]">Partial</option>
          <option value="overdue" className="bg-[oklch(0.20_0.03_270)]">Overdue</option>
        </select>
      </PField>
      <PField label="Payment type">
        <select value={type} onChange={(e) => setType(e.target.value)}
          className="w-full bg-transparent text-sm outline-none">
          <option value="monthly_fee" className="bg-[oklch(0.20_0.03_270)]">Monthly Fee</option>
          <option value="admission" className="bg-[oklch(0.20_0.03_270)]">Admission Charge</option>
          <option value="security_deposit" className="bg-[oklch(0.20_0.03_270)]">Security Deposit</option>
          <option value="misc" className="bg-[oklch(0.20_0.03_270)]">Miscellaneous</option>
        </select>
      </PField>
      <PField label="Payment method">
        <select value={method} onChange={(e) => setMethod(e.target.value)}
          className="w-full bg-transparent text-sm outline-none">
          <option value="cash" className="bg-[oklch(0.20_0.03_270)]">Cash</option>
          <option value="upi" className="bg-[oklch(0.20_0.03_270)]">UPI</option>
          <option value="bank_transfer" className="bg-[oklch(0.20_0.03_270)]">Bank Transfer</option>
        </select>
      </PField>
      <PField label="Payment date">
        <input type="date" value={date} onChange={(e) => setDate(e.target.value)}
          className="w-full bg-transparent text-sm outline-none" />
      </PField>
      <PField label="Due date (optional)">
        <input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)}
          className="w-full bg-transparent text-sm outline-none" />
      </PField>
      <div className="sm:col-span-2">
        <PField label="Notes (optional)">
          <textarea rows={2} value={notes} onChange={(e) => setNotes(e.target.value)}
            placeholder="Any remarks…" className="w-full resize-none bg-transparent text-sm outline-none" />
        </PField>
      </div>
      <button type="submit" disabled={busy}
        className="sm:col-span-2 mt-2 rounded-xl gradient-primary px-4 py-3 text-sm font-semibold text-white glow-violet disabled:opacity-60">
        {busy ? "Saving…" : initial ? "Save changes" : "Record payment"}
      </button>
    </form>
  );
}

function PField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <div className="mb-1.5 text-[11px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="rounded-xl glass px-3.5 py-2.5">{children}</div>
    </label>
  );
}

const MIGRATION_SQL = `-- Run in Supabase → SQL Editor → New query
CREATE TABLE IF NOT EXISTS public.payments (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  owner_id       UUID NOT NULL,
  student_id     UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  amount         NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  payment_type   TEXT NOT NULL DEFAULT 'monthly_fee',
  payment_method TEXT NOT NULL DEFAULT 'cash',
  payment_date   DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date       DATE,
  notes          TEXT,
  status         TEXT NOT NULL DEFAULT 'paid',
  receipt_number TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at     TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_payments_all" ON public.payments
  FOR ALL USING (owner_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.attendance_logs (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  owner_id    UUID NOT NULL,
  student_id  UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  date        DATE NOT NULL DEFAULT CURRENT_DATE,
  check_in    TIMESTAMPTZ,
  check_out   TIMESTAMPTZ,
  method      TEXT DEFAULT 'manual',
  notes       TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT attendance_unique_student_day UNIQUE (student_id, date)
);
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_attendance_all" ON public.attendance_logs
  FOR ALL USING (owner_id = auth.uid());`;
