/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CabinsRouteImport } from './routes/cabins'
import { Route as IndexRouteImport } from './routes/index'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsRoute = CabinsRouteImport.update({
  id: '/cabins',
  path: '/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabins': typeof CabinsRoute
  '/dashboard': typeof DashboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabins': typeof CabinsRoute
  '/dashboard': typeof DashboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabins': typeof CabinsRoute
  '/dashboard': typeof DashboardRoute
  '/renewals': typeof RenewalsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabins'
    | '/dashboard'
    | '/renewals'
    | '/settings'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabins' | '/dashboard' | '/renewals' | '/settings' | '/students'
  id:
    | '__root__'
    | '/'
    | '/cabins'
    | '/dashboard'
    | '/renewals'
    | '/settings'
    | '/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinsRoute: typeof CabinsRoute
  DashboardRoute: typeof DashboardRoute
  RenewalsRoute: typeof RenewalsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins': {
      id: '/cabins'
      path: '/cabins'
      fullPath: '/cabins'
      preLoaderRoute: typeof CabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinsRoute: CabinsRoute,
  DashboardRoute: DashboardRoute,
  RenewalsRoute: RenewalsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
